#ifndef GUI_CONFIG_H
#define GUI_CONFIG_H

#include <types.h>

#define GUI_SCREEN_WIDTH 1600
#define GUI_SCREEN_HEIGHT 900
#define GUI_SCREEN_BPP 32

#define DESKTOP_TASKBAR_BACKGROUND_COLOR 0xFF151515

#define WINDOW_BACKGROUND_COLOR 0xFF202020
#define WINDOW_SHADOW_COLOR_NORMAL 0x88000000
#define WINDOW_SHADOW_COLOR_FOCUSED 0xAA000000
#define WINDOW_TITLE_COLOR 0xFFFFFFFF
#define WINDOW_CLOSE_BUTTON_BACKGROUND_COLOR_NORMAL 0xFFCA0000
#define WINDOW_CLOSE_BUTTON_BACKGROUND_COLOR_PRESSED 0xFFBA0000
#define WINDOW_CLOSE_BUTTON_BACKGROUND_COLOR_HOVER 0xFFFFFFFF
#define WINDOW_CLOSE_BUTTON_BORDER_COLOR_NORMAL 0xFF470000
#define WINDOW_CLOSE_BUTTON_BORDER_COLOR_PRESSED 0xFF420000

#define BUTTON_BACKGROUND_COLOR_NORMAL 0xFF373737
#define BUTTON_BACKGROUND_COLOR_PRESSED 0xFF323232
#define BUTTON_BACKGROUND_COLOR_HOVER 0xFFFFFFFF
#define BUTTON_BORDER_COLOR_NORMAL 0xFF474747
#define BUTTON_BORDER_COLOR_PRESSED 0xFF424242
#define BUTTON_TEXT_COLOR_NORMAL 0xFFFFFFFF
#define BUTTON_TEXT_COLOR_PRESSED 0xFFe5e5e5

#define LABEL_TEXT_COLOR_NORMAL 0xFFFFFFFF

#define INPUT_BACKGROUND_COLOR_NORMAL 0xFF373737
#define INPUT_BACKGROUND_COLOR_ACTIVE 0xFF323232
#define INPUT_BACKGROUND_COLOR_HOVER 0xFFFFFFFF
#define INPUT_BORDER_COLOR_NORMAL 0xFFDDDDDD
#define INPUT_BORDER_COLOR_ACTIVE 0xFF0075D0
#define INPUT_TEXT_COLOR_NORMAL 0xFFe5e5e5
#define INPUT_TEXT_COLOR_ACTIVE 0xFFFFFFFF

#define MSGBOXWIDTH 300
#define MSGBOXHEIGHT 120

#endif  // GUI_CONFIG_H
