#ifndef GUI_CONFIG_H
#define GUI_CONFIG_H

#include <types.h>

#define DESKTOP_TASKBAR_BACKGROUND_COLOR 0xFF151515
#define WINDOW_BACKGROUND_COLOR 0xFF202020
#define WINDOW_TITLE_COLOR 0xFFFFFFFF

#define BUTTON_BACKGROUND_COLOR_NORMAL 0xFF373737
#define BUTTON_BACKGROUND_COLOR_PRESSED 0xFF323232
#define BUTTON_BACKGROUND_COLOR_HOVER 0xFFFFFFFF
#define BUTTON_BORDER_COLOR_NORMAL 0xFF474747
#define BUTTON_BORDER_COLOR_PRESSED 0xFF424242
#define BUTTON_TEXT_COLOR_NORMAL 0xFFFFFFFF
#define BUTTON_TEXT_COLOR_PRESSED 0xFFe5e5e5

#endif // GUI_CONFIG_H
